services:
   db:
     image: mariadb
     restart: always
     environment:
       MARIADB_ROOT_PASSWORD: somewordpress
       MARIADB_DATABASE: wordpress
       MARIADB_USER: wordpress
       MARIADB_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     build:
      context: ./wordpress
     healthcheck:
      test: [ "CMD-SHELL", "curl -f -I http://wordpress" ]
      interval: 10s
      timeout: 10s
      retries: 10
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       XDEBUG_CONFIG: client_host=10.197.1.85
     volumes:
       - ./wp-cassify:/usr/src/wordpress/wp-content/plugins/wp-cassify

   openldap:
     image: osixia/openldap:1.5.0
     environment:
       LDAP_DOMAIN: "example.org"
     command: --copy-service
     volumes:
      - ./ldap-config:/container/service/slapd/assets/config/bootstrap/ldif/custom

   cas:
     image: esupportail/apereo-cas-ldap:v6.6.0
     healthcheck:
      test: [ "CMD-SHELL", "curl -f -I http://cas:8080/cas" ]
      interval: 10s
      timeout: 10s
      retries: 10     
     volumes:
       - ./cas-config:/etc/cas
       - ./cas-config/tmp-cas:/tmp/cas
     ports:
       - "8080:8080"
     depends_on:
       - openldap

   selenium-chrome:
     image: selenium/standalone-chrome:125.0
     healthcheck:
       test: [ "CMD-SHELL", "curl -f -LI http://selenium-chrome:4444" ]
       interval: 10s
       timeout: 10s
       retries: 10    
     shm_size: 2gb
     ports:
       - '4444:4444'
    
   selenium-runner:
     build:
       context: selenium-runner
     depends_on:
       wordpress:
           condition: service_healthy
       selenium-chrome:
           condition: service_healthy
       cas:
           condition: service_healthy	   
     volumes:
       - './selenium-sides:/test-sides'


