version: '2'

services:
   db:
     image: mariadb
     restart: always
     environment:
       MARIADB_ROOT_PASSWORD: somewordpress
       MARIADB_DATABASE: wordpress
       MARIADB_USER: wordpress
       MARIADB_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     build:
      context: ./wordpress
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       XDEBUG_CONFIG: client_host=10.197.1.85

   openldap:
     image: osixia/openldap:1.5.0
     environment:
       LDAP_DOMAIN: "example.org"
     command: --copy-service
     volumes:
      - ./ldap-config:/container/service/slapd/assets/config/bootstrap/ldif/custom
     ports:
      - 3890:389

   cas:
     image: esupportail/apereo-cas-ldap:v6.6.0
     volumes:
       - ./cas-config:/etc/cas
       - ./cas-config/tmp-cas:/tmp/cas
     ports:
       - "8081:8080"
     depends_on:
       - openldap