name: Docker Selenium Tests for wordpress (php8)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: php8 run selenium tests in dockers env and stop it
      run: docker compose up --abort-on-container-exit
