name: Docker Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run selenium tests in dockers env and stop it
      run: docker compose up --abort-on-container-exit --force-recreate -V
